name: lint_no_list
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^4.2.0
  custom_lint_builder: ^0.0.9+1
  source_gen: ^1.2.2
